---
output:
  #bookdown::html_document2: default
  #bookdown::word_document2: default
  bookdown::pdf_document2: 
    template: templates/brief_template.tex
    citation_package: biblatex
documentclass: book
bibliography: references.bib
---
  
# Troubleshooting

This chapter describes common errors you may run into, and how to fix them.

## Error: Failed to build the bibliography via biber
This can happen if you've had a failed build, perhaps in relation to RStudio shutting down abruptly.

Try doing this:

1. type `make clean-knits` in the terminal tab (or run `file.remove(list.files(pattern = "*.(log|mtc|maf|aux|bbl|blg|xml)"))` in the R console) to clean up files generated by LaTeX during a build
2. then restart your computer 

This solved the problem for me, when I suddenly ran into this error after RStudio was abruptly shut down during a PDF build.

## TODO: the thing about icloud drive
- and how symlinks can help


## TODO: Add the thing about bibliography paths
- remove them in the individual chapter bibliography so that it doesn't override what is in index.Rmd