```{block type='savequote', include=knitr::opts_knit$get('rmarkdown.pandoc.to') == 'latex'}
Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...

There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...

\qauthor{--- Cicero's \textit{de Finibus Bonorum et Malorum}}
```

<!-- Note a gotcha in the savequote block: for the author, you have to use LaTeX syntax directly with \qauthor, and when doing so, you must also use LaTeX instead of Markdown syntax to, for example, italicise something inside \qauthor{} -->

# Some Final Notes on The OxThesis template
## Quotes by beginning of chapters
The OxThesis LaTeX template lets you add some wittiness to you thesis by including a block of type `savequote` at the beginning of chapters, using the syntax ```` ```{block type='savequote'} ````. You will probably also want to add the chunk option `include=knitr::opts_knit$get('rmarkdown.pandoc.to') == 'latex'` so these quotes are only included in PDF output.

For more on custom block types, see the relevant section in [_Authoring Books with R Markdown_](https://bookdown.org/yihui/bookdown/custom-blocks.html).

## Highlighting of corrections
The OxThesis template supplies two \LaTeX\ commands you can use directly in your .Rmd files if you only care about PDF output. First, the `mccorrect` command allows you to highlight a short correction \mccorrect{like this one}. When the thesis is typeset normally, the correction will just appear as part of the text. However, when you declare `corrections: yes` in **index.Rmd**, that correction will be highlighted in blue in PDF output. That might be useful for submitting a post-viva, corrected copy to your examiners so they can quickly verify you've completed the task. You must use \LaTeX\ rather than _R Markdown_ syntax inside of a `mccorrect` short correction.

The obvious problem is that raw LaTeX doesn't show up in HTML output, and we might want to showcase corrections in our gitbook output as well. To do that, the `oxforddown` template adds a little **R** function also named `mccorrect` that lets us do the same thing (this is created in the setup chunk that begins **index.Rmd**). [^hackish]

[^hackish]: This alternative, perhaps more hack-ish, route is taken from [this stack overflow tip](https://stackoverflow.com/questions/47298106/getting-r-printed-texts-to-have-color-esp-in-r-markdown-knits) and uses the function `text_spec` from the package `kableExtra` to apply a background color to corrections.

Now we can `r mccorrect("apply corrections *inline*")`using this function, which will apply the blue corrections background color in both PDF and HTML output. [^argh]

[^argh]: It seems this in turn has the bug that the asterisks will correctly be turned into italics on HTML output, but will be rendered literally with LaTeX... FML.

For larger chunks, you can put them in a block of type `mccorrection` (which in the **.tex** file for PDF output will put the content between `\begin{mccorrection}` and `\end{mccorrection}`, and in the HTML file for gitbook output between `<div class="mccorrection">` and `</div>`. Rather than doing it directly, we use params$corrections to set it from the YAML header in **index.Rmd**.

```{block type=params$corrections}
For larger chunks, like this paragraph or indeed entire figures, you can use the `mccorrection` environment. This environment **highlights paragraph-sized and larger blocks** with the same blue colour.
```

<!-- NOTE: if you're trying to output as word doc, this block may cause an error in compilation - you can avoid this by adding the chunk option include=knitr::opts_knit$get('rmarkdown.pandoc.to') == 'latex' which will exclude it from word output-->

## Diving in to the OxThesis LaTeX template
For LaTeX minded people, you can read through **templates/template.tex** to understand which additional customisation options are available in there as well as in **templates/ociamthesis.cls** which supplies the base class.  For example, **template.tex** provides a separate option for master's degree submissions, which changes identifying information to candidate number and includes a word count. At the time of writing, you must set these directly in **template.tex** rather than from the YAML header in **index.Rmd**.

## Collaborative writing
Best practices for collaboration and change tracking when using R Markdown are still an open question. In the blog post [**One year to dissertate**](https://livefreeordichotomize.com/2018/09/14/one-year-to-dissertate/) by Lucy D'Agostino, which I highly recommend, the author notes how she would knit .Rmd files to a `word_document`, then use the `googledrive` R package to send this to Google Drive for comments / revisions from co-authors, then incorporate Google Drive suggestions *by hand* into the .Rmd source files. This is a bit clunky, and there are ongoing discussions among the _R Markdown_ developers about what the best way is to handle collaborative writing (see [issue #1463](https://github.com/rstudio/rmarkdown/issues/1463) on GitHub, with [CriticMarkup](http://criticmarkup.com) being among the suggestions. 

For now, this is still an open question in the community of R Markdown users. Knitting to a format that can easily be imported to Google Docs for comments, then going over suggested revisions and manually incorporating them back in to the .Rmd source files, has worked ok for me personally. For article writing, I sometimes upload the near-final draft to [Overleaf](https://www.overleaf.com/), then collaboratively make final edits to the \LaTeX\ file in there. I suspect some great solution will be developed in the not-to-distant future, probably by the RStudio team.